# Generated by Django 5.2.1 on 2025-06-11 16:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text="Addresse e-mail de l'utilisateur", max_length=255, unique=True, verbose_name='Adresse e-mail')),
                ('phone_number', models.CharField(blank=True, help_text="Numéro de téléphone de l'utilisateur", max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('role', models.CharField(choices=[('student', 'Étudiant'), ('professor', 'Professeur')], default='student', max_length=10, verbose_name="Rôle de l'utilisateur")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur ESIACBOOK',
                'verbose_name_plural': 'Utilisateurs ESIACBOOK',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='Identifiant unique du professeur', max_length=50, null=True, unique=True, verbose_name='Numero Employé')),
                ('department', models.CharField(blank=True, help_text="Département d'enseignement du professeur", max_length=100, null=True, verbose_name='Département')),
                ('specialization', models.CharField(blank=True, help_text='Spécialisation du professeur', max_length=100, null=True, verbose_name='Spécialisation')),
                ('profil_photo', models.ImageField(blank=True, default='professor_profiles/default_profile.png', help_text='Photo de profil du professeur', null=True, upload_to='profile_photos/professors/', verbose_name='Photo de profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Professeur')),
            ],
            options={
                'verbose_name': 'Profil Professeur',
                'verbose_name_plural': 'Profils Professeurs',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, help_text=" matricule unique de l'étudiant", max_length=50, null=True, unique=True, verbose_name='Numero matricule')),
                ('major', models.CharField(blank=True, help_text='Genie Logiel, Reseaux et Telecoms', max_length=100, null=True, verbose_name='Filiere / Spécialité')),
                ('level', models.CharField(blank=True, help_text='Ex: Licence 1, Master 2, etc.', max_length=50, null=True, verbose_name="Niveau d'étude")),
                ('profil_photo', models.ImageField(blank=True, default='student_profiles/default_profile.png', help_text="Photo de profil de l'étudiant", null=True, upload_to='profile_photos/students/', verbose_name='Photo de profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Etudiant')),
            ],
            options={
                'verbose_name': 'Profil Étudiant',
                'verbose_name_plural': 'Profils Étudiants',
                'ordering': ['user__last_name'],
            },
        ),
    ]
