# Generated by Django 5.2.1 on 2025-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorprofile',
            name='profil_photo',
            field=models.ImageField(blank=True, default='media/professor_profiles/default_profile.png', help_text='Photo de profil du professeur', null=True, upload_to='profile_photos/professors/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profil_photo',
            field=models.ImageField(blank=True, default='media/student_profiles/default_profile.png', help_text="Photo de profil de l'étudiant", null=True, upload_to='profile_photos/students/', verbose_name='Photo de profil'),
        ),
    ]
