# Generated by Django 5.2.1 on 2025-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_professorprofile_profil_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorprofile',
            name='profil_photo',
            field=models.ImageField(blank=True, default='', help_text='Photo de profil du professeur', null=True, upload_to='profile_photos/professors/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profil_photo',
            field=models.ImageField(blank=True, default='', help_text="Photo de profil de l'étudiant", null=True, upload_to='profile_photos/students/', verbose_name='Photo de profil'),
        ),
    ]
