# Generated by Django 5.2.1 on 2026-08-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_professorprofile_profil_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=True, help_text="Pour un professeur, doit être validé par un admin avant d'avoir les privilèges professeur.", verbose_name='Compte vérifié par un administrateur'),
        ),
    ]
