# Generated by Django 5.2.1 on 2025-06-16 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la ressource')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='media/resources_files/', verbose_name='Fichier de la ressource')),
                ('resource_type', models.CharField(choices=[('course', 'Cours'), ('td', 'TD'), ('exam', 'Examen'), ('other', 'Autre')], default='course', max_length=10, verbose_name='Type de ressource')),
                ('subject', models.CharField(max_length=100, verbose_name='Matière')),
                ('level', models.CharField(max_length=50, verbose_name="Niveau d'étude")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='Uploader par')),
            ],
            options={
                'verbose_name': 'Ressource Pédagogique',
                'verbose_name_plural': 'Ressources Pédagogiques',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
