# Generated by Django 5.2.1 on 2025-06-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_rename_ressources_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources_files/', verbose_name='Fichier de la ressource'),
        ),
    ]
