# Generated by Django 5.2.1 on 2025-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_alter_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('exam', 'Examen'), ('other', 'Autre')], default='cours', max_length=10, verbose_name='Type de ressource'),
        ),
    ]
